# Generated by Django 5.2.8 on 2025-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneno', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('borrowDate', models.DateField()),
                ('returnDate', models.DateField()),
            ],
            options={
                'db_table': 'borrowerdetails',
            },
        ),
    ]
