# Generated by Django 5.2.8 on 2025-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklender', '0002_borrowerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerdetails',
            name='username',
            field=models.CharField(default='temp', max_length=30),
            preserve_default=False,
        ),
    ]
