# Generated by Django 5.2.8 on 2025-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklender', '0004_addbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=200)),
                ('review_text', models.TextField(max_length=500)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
