# Generated by Django 5.2.8 on 2025-11-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklender', '0006_reviewlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlist',
            name='user',
        ),
    ]
