# Generated by Django 5.2.8 on 2025-11-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklender', '0007_remove_reviewlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
