# Generated by Django 5.2.8 on 2025-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklender', '0008_addbook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
